/**
 * Lista marek do wyboru przy wystawianiu (styl Vinted) — alfabetycznie.
 * Picker ma wyszukiwarkę, więc długa lista jest OK. „Inna" na końcu = własna nazwa.
 */
export const BRANDS: string[] = [
  '& Other Stories', '4F', 'Acne Studios', 'Adidas', 'Aldo', 'Alexander McQueen',
  'Anna Field', 'Apart', "Arc'teryx", 'Armani Exchange', 'Asics', 'ASOS', 'Badura',
  'Balenciaga', 'Balmain', 'Bape', 'Bench', 'Benetton', 'Berghaus', 'Bershka',
  'Big Star', 'Birkenstock', 'Bohoboco', 'Boohoo', 'Born2be', 'Boss', 'Bottega Veneta',
  'Burberry', 'Bvlgari', 'Bytom', 'C&A', 'Calvin Klein', 'Calzedonia', 'Camaieu',
  'Carhartt', 'Cartier', 'Casio', 'Caterpillar', 'CCC', 'Celine', 'Champion', 'Chanel',
  'Christian Louboutin', 'Clarks', 'CMP', 'Coach', 'Coccodrillo', 'Columbia',
  'Comme des Garçons', 'Converse', 'Corteiz', 'COS', 'Cropp', 'Cross Jeans',
  'Daniel Wellington', 'DC', 'Decathlon', 'Deichmann', 'Desigual', 'Diadora', 'Dickies',
  'Diesel', 'Dior', 'Diverse', 'Dolce & Gabbana', 'Dr. Martens', 'Ecco', 'Element',
  'Ellesse', 'Emporio Armani', 'Endo', 'Esotiq', 'Esprit', 'Etam', 'Fendi', 'Fila',
  'Fjällräven', 'Forever 21', 'Fossil', 'Furla', 'Gant', 'Gap', 'Geox', 'Gina Tricot',
  'Gino Rossi', 'Givenchy', 'Greenpoint', 'G-Star Raw', 'Gucci', 'Guess', 'H&M',
  'Helly Hansen', 'Hermès', 'House', 'HUF', 'Hugo', 'Hugo Boss', 'Hummel', 'Hunkemöller',
  'Intimissimi', 'Jack & Jones', 'Jack Wolfskin', 'Jenny Fairy', 'Jimmy Choo', 'Jordan',
  'Kappa', 'KappAhl', 'Karl Lagerfeld', 'Kazar', 'Kenzo', 'Lacoste', 'Lasocki', 'Lee',
  "Levi's", 'Lindex', 'Liu Jo', 'Local Heroes', 'Loewe', 'Longchamp', 'Lotto',
  'Louis Vuitton', 'Mango', 'Marc Jacobs', "Marc O'Polo", 'Marmot', 'Massimo Dutti',
  'Medicine', 'Michael Kors', 'MISBHV', 'Missguided', 'Mizuno', 'Mohito', 'Moncler',
  'Monki', 'Monnari', 'Moschino', 'Mustang', 'Name It', 'Napapijri', 'New Balance',
  'New Yorker', 'Nike', 'Obey', 'Ochnik', 'Off-White', 'Only', 'Orsay', 'Palace',
  'Pandora', 'Patagonia', 'Patrizia Pepe', 'Pepe Jeans', 'Pieces', 'Pinko',
  'Polo Ralph Lauren', 'Prada', 'PrettyLittleThing', 'Primark', 'Promod', 'Próchnik',
  'Pull&Bear', 'Puma', 'Quiosque', 'Ralph Lauren', 'Reebok', 'Recman', 'Replay',
  'Represent', 'Reserved', 'Risk', 'River Island', 'Ryłko', 's.Oliver', 'Saint Laurent',
  'Salomon', 'Scotch & Soda', 'Selected', 'Sergio Tacchini', 'Shein', 'Simple', 'Sinsay',
  'Skechers', 'Smyk', 'Stone Island', 'Stradivarius', 'Stüssy', 'Superdry', 'Supreme',
  'Swarovski', 'Tally Weijl', 'Tatuum', 'Ted Baker', 'The North Face', 'Thrasher',
  'Timberland', 'Tom Tailor', 'Tommy Hilfiger', 'Tommy Jeans', 'Top Secret', 'Topman',
  'Topshop', 'Tory Burch', 'Tous', 'Triumph', 'True Religion', 'Twinset', 'UGG', 'Umbro',
  'Under Armour', 'Uniqlo', 'Valentino', 'Vans', 'Vero Moda', 'Versace',
  "Victoria's Secret", 'Vistula', 'Vivienne Westwood', 'Wittchen', 'Wojas', 'Wrangler',
  'Yeezy', 'Zara', 'Zign',
  'Inna',
];
